version: '3.4'

services:
  nedrex_biocypher:
    build: .
    container_name: nedrex_biocypher
    user: '0'
    environment:
      - NEO4J_AUTH=neo4j/neo4jpassword
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
 #   restart: always

