version: '3.4'

services:
  nedrex_biocypher:
    build: .
    container_name: nedrex_biocypher
    user: '0'
    env_file:
      - docker_variables.env
    volumes:
      - nedrexv1_bc_data:/data
    ports:
      - 7474:7474
      - 7687:7687
volumes:
  nedrexv1_bc_data:
 #   restart: always

