version: '3.3'

services:
  neo4j:
    build: .
    container_name: nedrex_biocypher
    env_file:
      - docker-variables.env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - nedrexv1_bc_data:/data
 #   restart: always

volumes:
  nedrexv1_bc_data: