# add your settings here (overriding the defaults)

biocypher:
  offline: true
  strict_mode: true
  output_directory: biocypher-out/nedrex

neo4j:
  database_name: nedrex
  delimiter: '\t'
  array_delimiter: '|'
  wipe: true
  import_call_file_prefix: import/nedrex/
  quote_character: '"'
