# ---
# "Named Things"
# ---
drug:
  represented_as: node
  preferred_id: drugbank
  label_in_input: drugbank
  properties:
    displayName: str
    allDatasets: str[]
    casNumber: str
    description: str
    domainIds: str[]
    drugCategories: str[]
    drugGroups: str[]
    indication: str
    iupacName: str
    primaryDataset: str
    sequences: str[]
    synonyms: str[]
    inchi: str
    molecularFormula: str
    smiles: str

disorder:
  is_a: disease
  represented_as: node
  preferred_id: mondo
  label_in_input: mondo
  properties:
    displayName: str
    domainIds: str[]
    synonyms: str[]
    icd10: str[]
    description: str

gene:
  represented_as: node
  preferred_id: entrez
  label_in_input: entrez
  properties:
    displayName: str
    domainIds: str[]
    synonyms: str[]
    approvedSymbol: str
    symbols: str[]
    description: str
    chromosome: str
    mapLocation: str
    geneType: str

protein:
  represented_as: node
  preferred_id: uniprot
  label_in_input: uniprot
  properties:
    domainIds: str
    sequence: str
    displayName: str
    synonyms: str[]
    comments: str
    geneName: str
    taxid: int

pathway:
  represented_as: node
  preferred_id: reactome
  label_in_input: reactome
  properties:
    displayName: str
    domainIds: str[]
    species: str

signature:
  is_a: nucleic acid sequence motif
  represented_as: node
  preferred_id: prosite
  label_in_input: prosite
  properties:
    description: str


# ---
# Associations
# ---
drug indicated for disease:
  is_a: chemical or drug or treatment to disease or phenotypic feature association
  represented_as: edge
  label_in_input: DrugHasIndication
  properties:
    version: str[]
    licence: str[]
    source: str[]

disorder is subtype of disorder:
  is_a: entity to disease association
  represented_as: edge
  label_in_input: DisorderIsSubtypeOfDisorder
  properties:
    version: str[]
    licence: str[]
    source: str[]

drug contraindicated for disease:
  is_a: chemical or drug or treatment to disease or phenotypic feature association
  represented_as: edge
  label_in_input: DrugHasContraindication
  properties:
    version: str[]
    licence: str[]
    source: str[]

drug has target protein:
  is_a: drug to gene association
  represented_as: edge
  label_in_input: DrugHasTarget
  properties:
    version: str[]
    licence: str[]
    source: str[]
    actions: str[]
    databases: str[]

gene associated with disorder:
  is_a: gene to disease association
  represented_as: edge
  label_in_input: GeneAssociatedWithDisorder
  properties:
    version: str[]
    licence: str[]
    source: str[]
    assertedBy: str[]
    score: double

protein is isoform of protein:
  is_a: gene to gene association
  represented_as: edge
  label_in_input: IsIsoformOf
  properties:
    version: str[]
    licence: str[]
    source: str[]

drug similarity:
  is_a: chemical to chemical association
  represented_as: edge
  label_in_input: MoleculeSimilarityMolecule
  properties:
    version: str[]
    licence: str[]
    source: str[]
    morganR1: double
    morganR2: double
    morganR3: double
    morganR4: double
    maccs: double

protein is encoded by gene:
  is_a: gene to gene product relationship
  represented_as: edge
  label_in_input: ProteinEncodedBy
  properties:
    version: str[]
    licence: str[]
    source: str[]

protein has signature:
  is_a: sequence association
  represented_as: edge
  label_in_input: ProteinHasSignature
  properties:
    version: str[]
    licence: str[]
    source: str[]

protein is in pathway:
  is_a: gene to pathway association
  represented_as: edge
  label_in_input: ProteinInPathway
  properties:
    version: str[]
    licence: str[]
    source: str[]

protein interacts with protein:
  is_a: gene to gene association
  represented_as: edge
  label_in_input: ProteinInteractsWithProtein
  properties:
    version: str[]
    licence: str[]
    source: str[]
    methods: str[]
    databases: str[]
    evidenceTypes: str[]

protein is similar to protein:
  is_a: gene to gene association
  represented_as: edge
  label_in_input: ProteinSimilarityProtein
  properties:
    version: str[]
    licence: str[]
    source: str[]
    blast12_query: str
    blast12_hit: str
    blast12_bitscore: double
    blast12_evalue: double
    blast12_queryStart: int
    blast12_queryEnd: int
    blast12_hitStart: int
    blast12_hitEnd: int
    blast12_identity: double
    blast12_mismatches: int
    blast12_gaps: int
    blast12_queryCover: double
    blast12_hitCover: double
    blast12_type: str
    blast21_query: str
    blast21_hit: str
    blast21_bitscore: double
    blast21_evalue: double
    blast21_queryStart: int
    blast21_queryEnd: int
    blast21_hitStart: int
    blast21_hitEnd: int
    blast21_identity: double
    blast21_mismatches: int
    blast21_gaps: int
    blast21_queryCover: double
    blast21_hitCover: double
    blast21_type: str